@hostname = localhost
@port = 7257
@host = {{hostname}}:{{port}}
@contentType = application/json

### Find - Empty result
GET https://{{host}}/api/Distrito/Find?codigo=00
Content-Type: {{contentType}}


### Find - One result
GET https://{{host}}/api/Distrito/Find?nome=GRANDE&codigo=16
Content-Type: {{contentType}}


### Find - Many results
GET https://{{host}}/api/Distrito/Find?nome=CAMPO
Content-Type: {{contentType}}






### GetByCodigo - Result Ok
GET https://{{host}}/api/Distrito/GetByCodigo/17
Content-Type: {{contentType}}


### GetByCodigo - Error result (not found)
GET https://{{host}}/api/Distrito/GetByCodigo/00
Content-Type: {{contentType}}


### GetByCodigo - Error result (wrong parameter)
GET https://{{host}}/api/Distrito/GetByCodigo/0123456789
Content-Type: {{contentType}}