@hostname = localhost
@port = 7257
@host = {{hostname}}:{{port}}
@contentType = application/json

### Find - Empty result
POST https://{{host}}/api/Distrito/Find
Content-Type: {{contentType}}

{
	"codigo" : "00"
}


### Find - One result
POST https://{{host}}/api/Distrito/Find
Content-Type: {{contentType}}

{
	"nome" : "GRANDE",
	"codigo" : "16"
}


### Find - Many results
POST https://{{host}}/api/Distrito/Find
Content-Type: {{contentType}}

{
	"nome" : "CAMPO"
}








### GetByCodigo - Result Ok
POST https://{{host}}/api/Distrito/GetByCodigo
Content-Type: {{contentType}}

{
	"codigo" : "17"
}


### GetByCodigo - Error result (not found)
POST https://{{host}}/api/Distrito/GetByCodigo
Content-Type: {{contentType}}

{
	"codigo" : "00"
}


### GetByCodigo - Error result (wrong parameter)
POST https://{{host}}/api/Distrito/GetByCodigo
Content-Type: {{contentType}}

{
	"codigo" : "0058858585858585747474"
}