@hostname = localhost
@port = 7257
@host = https://{{hostname}}:{{port}}
@contentType = application/json

### Find - Empty result
POST {{host}}/api/Feira/Find
Content-Type: {{contentType}}

{
	"nome"        : "feira inexistente",
	"codDistrito" : "01",
	"regiao5"     : 2,
	"bairro"      : "MOOCA"
}


### Find - One result
POST {{host}}/api/Feira/Find
Content-Type: {{contentType}}

{
	"nome" : "AGUA BRANCA"
}


### Find - Many results
POST {{host}}/api/Feira/Find
Content-Type: {{contentType}}

{
	"nome"        : "VILA",
	"codDistrito" : "04"
}
