@hostname = localhost
@port = 7257
@host = {{hostname}}:{{port}}
@contentType = application/json

### Find - Empty result
POST https://{{host}}/api/SubPrefeitura/Find
Content-Type: {{contentType}}

{
	"codigo" : "00"
}


### Find - One result
POST https://{{host}}/api/SubPrefeitura/Find
Content-Type: {{contentType}}

{
	"nome" : "MOOCA",
	"codigo" : "25"
}


### Find - Many results
POST https://{{host}}/api/SubPrefeitura/Find
Content-Type: {{contentType}}

{
	"nome" : "VILA"
}








### GetByCodigo - Result Ok
POST https://{{host}}/api/SubPrefeitura/GetByCodigo
Content-Type: {{contentType}}

{
	"codigo" : "17"
}


### GetByCodigo - Error result (not found)
POST https://{{host}}/api/SubPrefeitura/GetByCodigo
Content-Type: {{contentType}}

{
	"codigo" : "00"
}


### GetByCodigo - Error result (wrong parameter)
POST https://{{host}}/api/SubPrefeitura/GetByCodigo
Content-Type: {{contentType}}

{
	"codigo" : "0058858585858585747474"
}